import {PrismaClient} from '@prisma/client'; import bcrypt from 'bcryptjs'; import crypto from 'crypto';
const p=new PrismaClient();
async function main(){
 await p.orderStatusHistory.deleteMany();await p.orderItem.deleteMany();await p.order.deleteMany();await p.customerAddress.deleteMany();await p.customer.deleteMany();await p.productModifierGroup.deleteMany();await p.modifierOption.deleteMany();await p.modifierGroup.deleteMany();await p.product.deleteMany();await p.category.deleteMany();await p.coupon.deleteMany();await p.deliveryZone.deleteMany();await p.apiKey.deleteMany();await p.user.deleteMany();await p.establishment.deleteMany();
 const e=await p.establishment.create({data:{name:'Sabor & Brasa',slug:'sabor-e-brasa',email:'contato@saborebrasa.com',phone:'(18) 99999-0000',whatsapp:'5518999990000',description:'Hambúrgueres artesanais, porções e bebidas.',primaryColor:'#ff6b2c',minimumOrder:25,averagePreparationTime:32,address:'Av. Brasil, 500',city:'Presidente Prudente',state:'SP'}});
 await p.user.create({data:{establishmentId:e.id,name:'Alan Silva',email:'admin@demo.com',passwordHash:await bcrypt.hash('Admin123!',10),role:'OWNER'}});
 await p.user.createMany({data:[{establishmentId:e.id,name:'Marina Costa',email:'gerente@demo.com',passwordHash:await bcrypt.hash('Admin123!',10),role:'MANAGER'},{establishmentId:e.id,name:'João Cozinha',email:'cozinha@demo.com',passwordHash:await bcrypt.hash('Admin123!',10),role:'KITCHEN'}]});
 const cats=[];for(const c of [{name:'Hambúrgueres',description:'Smash e artesanais',sortOrder:1},{name:'Combos',description:'Combos completos',sortOrder:2},{name:'Porções',description:'Para compartilhar',sortOrder:3},{name:'Bebidas',description:'Geladas',sortOrder:4}])cats.push(await p.category.create({data:{...c,establishmentId:e.id}}));
 const imgs=['https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80'];
 const prods=[];for(const x of [
 {categoryId:cats[0].id,name:'Brasa Bacon',description:'Pão brioche, carne 160g, cheddar, bacon crocante e molho da casa.',price:29.9,promotionalPrice:25.9,featured:true,imageUrl:imgs[0],sku:'BUR-001',tags:['Mais vendido']},
 {categoryId:cats[0].id,name:'Duplo Smash',description:'Dois smash 100g, queijo duplo, cebola caramelizada e picles.',price:34.9,imageUrl:imgs[1],sku:'BUR-002',tags:['Artesanal']},
 {categoryId:cats[0].id,name:'Chicken Crispy',description:'Frango empanado, alface, queijo e maionese temperada.',price:27.9,imageUrl:imgs[0],sku:'BUR-003',tags:['Crocante']},
 {categoryId:cats[1].id,name:'Combo Brasa',description:'Brasa Bacon + fritas P + refrigerante lata.',price:39.9,promotionalPrice:36.9,featured:true,imageUrl:imgs[1],sku:'COM-001',tags:['Combo']},
 {categoryId:cats[2].id,name:'Batata com Cheddar',description:'Batata crocante com cheddar cremoso e bacon.',price:24.9,imageUrl:imgs[2],sku:'POR-001',tags:['Compartilhar']},
 {categoryId:cats[2].id,name:'Onion Rings',description:'Anéis de cebola empanados com molho barbecue.',price:19.9,imageUrl:imgs[2],sku:'POR-002',tags:[]},
 {categoryId:cats[3].id,name:'Coca-Cola 350ml',description:'Lata gelada.',price:7,imageUrl:imgs[3],sku:'BEB-001',tags:[]},
 {categoryId:cats[3].id,name:'Suco de Laranja 500ml',description:'Natural, feito na hora.',price:12,imageUrl:imgs[3],sku:'BEB-002',tags:['Natural']}
 ])prods.push(await p.product.create({data:{...x,establishmentId:e.id,available:true,trackStock:false,preparationTime:25}}));
 const group=await p.modifierGroup.create({data:{establishmentId:e.id,name:'Adicionais',maxSelect:4,options:{create:[{name:'Bacon extra',price:5},{name:'Cheddar extra',price:4},{name:'Carne extra',price:9},{name:'Molho especial',price:2}]}}});await p.productModifierGroup.createMany({data:prods.slice(0,4).map(x=>({productId:x.id,groupId:group.id}))});
 const customers=[];for(const c of [{name:'Carlos Eduardo',phone:'18998887766',email:'carlos@email.com'},{name:'Fernanda Lima',phone:'18997776655',email:'fernanda@email.com'},{name:'Rafael Souza',phone:'18996665544',email:'rafael@email.com'},{name:'Juliana Martins',phone:'18995554433',email:'juliana@email.com'}])customers.push(await p.customer.create({data:{...c,establishmentId:e.id}}));
 for(const c of customers)await p.customerAddress.create({data:{customerId:c.id,label:'Casa',zipCode:'19000-000',street:'Rua das Flores',number:String(100+customers.indexOf(c)),neighborhood:'Centro',city:'Presidente Prudente',state:'SP',primary:true}});
 const statuses=['PENDING','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED','COMPLETED'] as const;
 for(let i=0;i<18;i++){const product=prods[i%prods.length],cust=customers[i%customers.length],qty=(i%3)+1,total=Number(product.promotionalPrice??product.price)*qty;const created=new Date();created.setDate(created.getDate()-(i%7));created.setHours(10+(i%10),i*3%60);await p.order.create({data:{establishmentId:e.id,customerId:cust.id,addressId:(await p.customerAddress.findFirst({where:{customerId:cust.id}}))!.id,orderNumber:1001+i,channel:i%3===0?'WHATSAPP':'WEBSITE',status:statuses[i%statuses.length],deliveryType:i%4===0?'PICKUP':'DELIVERY',paymentMethod:i%2===0?'PIX':'CREDIT_CARD',paymentStatus:i%5===0?'PENDING':'PAID',subtotal:total,deliveryFee:i%4===0?0:6,total:total+(i%4===0?0:6),createdAt:created,items:{create:{productId:product.id,productNameSnapshot:product.name,unitPrice:Number(product.promotionalPrice??product.price),quantity:qty,subtotal:total}},history:{create:{to:statuses[i%statuses.length],origin:'SEED'}}}})}
 await p.coupon.createMany({data:[{establishmentId:e.id,code:'BEMVINDO10',description:'10% na primeira compra',discountType:'PERCENT',discountValue:10,minimumOrder:30,maxUses:500},{establishmentId:e.id,code:'FRETEGRATIS',description:'R$ 6 de desconto',discountType:'FIXED',discountValue:6,minimumOrder:45,maxUses:200}]});
 await p.deliveryZone.createMany({data:[{establishmentId:e.id,name:'Centro',neighborhoods:['Centro','Vila Marcondes'],fee:5,minimumOrder:20,estimatedMinutes:35},{establishmentId:e.id,name:'Zona Sul',neighborhoods:['Jardim Bongiovani','Parque do Povo'],fee:8,minimumOrder:30,estimatedMinutes:50}]});
 const key='demo_delivery_key_123';await p.apiKey.create({data:{establishmentId:e.id,name:'Integração n8n',keyHash:crypto.createHash('sha256').update(key).digest('hex'),prefix:'demo_del',permissions:['menu:read','orders:write']}});
 console.log('Seed V3 concluído.\nLogin: admin@demo.com / Admin123!\nLoja: http://localhost:5173/loja\nX-API-Key: demo_delivery_key_123');
}main().finally(()=>p.$disconnect());
